### ISSUE TITLE
Small Grants period is wrong

### ISSUE THREAD

**Issue by moba** [muesli/polly#26]
Currently, it looks like we're using "every second month" as: February, April, June, ...
Since we launched in February instead, users expect: March, May, July, ...

So, we need to shift everything one month. I hope this is not too much effort.

I will create a second ticket for the display issue (Poll End Date displayed instead of Poll Start Date).

**Comment by moba** [comment]
( Ah, I already created that last night: #21 )

**Comment by moba** [comment]
I updated the ticket, disregard the earlier proposed fixed.

**Comment by muesli** [comment]
Adjust Config.App.Proposals.StartMonth to the desired starting month.
