### ISSUE TITLE
Leave micro grants running for full 14 day period regardless of downvotes

### ISSUE THREAD

**Issue by moba** [muesli/polly#28]
I don't know if that's currently the case, because we discussed different variants, but we should keep micro grant proposals running for the full 14 days and not immediately reject them when 5 downvotes are reached. 

Edit: Moved suggestion for "ended" proposal to new ticket (#30).

**Comment by moba** [comment]
Currently, with 5 downvotes, proposals are shown not under "running", but under "rejected". We should change this so they still show as "running", until they are actually rejected after the full runtime.

**Comment by muesli** [comment]
Done.
